### ISSUE TITLE
After updating to .Net Core 2 receiving the following error upon running the application

### ISSUE THREAD

**Issue by atiwari3** [rh072005/SwashbuckleAspNetVersioningShim#12]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.) ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiVersionDescriptionProvider.EnumerateApiVersions(IActionDescriptorCollectionProvider actionDescriptorCollectionProvider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at SwashbuckleAspNetVersioningShim.SwaggerVersioner.ConfigureSwaggerVersions(SwaggerUIOptions swaggerUIOptions, IApiVersionDescriptionProvider provider, SwaggerVersionOptions versionOptions)
   at Nc.Api.Startup.NcApiBaseStartup`1.ConfigureSwaggerUi(SwaggerUIOptions swaggerUiOptions, IApiVersionDescriptionProvider apiVersions) in C:\git\nc.api.portal\Nc.Api\Nc.Api\Startup\NcApiBaseStartup.cs:line 440
   at Nc.Api.Startup.NcApiBaseStartup`1.<ConfigureApplication>b__14_0(SwaggerUIOptions x) in C:\git\nc.api.portal\Nc.Api\Nc.Api\Startup\NcApiBaseStartup.cs:line 187
   at Microsoft.AspNetCore.Builder.SwaggerUIBuilderExtensions.UseSwaggerUI(IApplicationBuilder app, Action`1 setupAction)
   at Nc.Api.Startup.NcApiBaseStartup`1.ConfigureApplication(IApplicationBuilder applicationBuilder) in C:\git\nc.api.portal\Nc.Api\Nc.Api\Startup\NcApiBaseStartup.cs:line 187
   at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.InjectApiVersionRoutePolicy.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AspNetCore.CleanStart.Server`1.<RunAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---

**Comment by PaddoSwam** [comment]
Thanks for the issue report, I'll investigate this tonight! :)

**Comment by rh072005** [comment]
@PaddoSwam cheers for taking a look at this, much appreciated 😄 

I've also had a look into this and haven't been able to reproduce the error.
This issue was also a reminder for me to start upgrading this to dotnet 2.0. To that end I've just pushed an update that upgrades everything to 2.0 and it's now available as 2.0.0-beta1.
I'm hoping that the upgraded version may solve this issue but let me know how it goes @atiwari3

**Comment by atiwari3** [comment]
No dice unfortunately. I'll try and see if I can find some more information.

**Comment by rh072005** [comment]
Have you got any code samples you can share? The most useful parts would be your Startup.cs and an example controller

**Comment by atiwari3** [comment]
Nvm guys. Seems like the problem was in inconsistent versioning of packages on my end.  I'll let ya'll know if something else comes up. Thanks for the help.

**Comment by rh072005** [comment]
No worries, give us a shout if you need
